/**
 * Bó Ver
 * Documentação para API Bó Ver
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("RoomsApi", () => {
  let instance: api.RoomsApi
  beforeEach(function() {
    instance = new api.RoomsApi(config)
  });

  test("roomsControllerCreate", () => {
    const body: api.CreateRoomDto = undefined
    return expect(instance.roomsControllerCreate(body, {})).resolves.toBe(null)
  })
  test("roomsControllerFindAll", () => {
    return expect(instance.roomsControllerFindAll({})).resolves.toBe(null)
  })
  test("roomsControllerFindOne", () => {
    const id: string = "id_example"
    return expect(instance.roomsControllerFindOne(id, {})).resolves.toBe(null)
  })
})

